version: '2'
services:
  php:
    container_name: "safetruck-front"
    image: nginx:alpine
    volumes:
     - ./dist:/usr/share/nginx/html
    ports:
     - "8080:80"
     - "443:443"
volumes:
  data:
    driver: "local"