version: '2'
services:
  server:
    container_name: "safetruck-front"
    build:
      context: .
    image: safetruck-container
    ports:
     - "8080:80"
     - "443:443"
volumes:
  data:
    driver: "local"